SELECT
    CON.'CONTEST_ID',
    CON.'HACKER_ID',
    CON.'NAME',
    COALESCE(SUM(SG.'TOTAL_SUBMISSIONS'), 0) AS 'TOTAL_SUBMISSIONS',
    COALESCE(SUM(SG.'TOTAL_ACCEPTED_SUBMISSIONS'), 0) AS 'TOTAL_ACCEPTED_SUBMISSIONS',
    COALESCE(SUM(VG.'TOTAL_VIEWS'), 0) AS 'TOTAL_VIEWS',
    COALESCE(SUM(VG.'TOTAL_UNIQUE_VIEWS'), 0) AS 'TOTAL_UNIQUE_VIEWS'
FROM 'CONTESTS' CON
    INNER JOIN 'COLLEGES' COL ON CON.'CONTEST_ID' = COL.'CONTEST_ID'
    INNER JOIN 'CHALLENGES' CHA ON COL.'COLLEGE_ID' = CHA.'COLLEGE_ID'
    LEFT JOIN (
      SELECT
        V.'CHALLENGE_ID',
        SUM(V.'TOTAL_VIEWS') AS 'TOTAL_VIEWS',
        SUM(V.'TOTAL_UNIQUE_VIEWS') AS 'TOTAL_UNIQUE_VIEWS'
      FROM 'VIEW_STATS' V
      GROUP BY V.'CHALLENGE_ID'
    ) VG ON CHA.'CHALLENGE_ID' = VG.'CHALLENGE_ID'
    LEFT JOIN (
      SELECT
        S.'CHALLENGE_ID',
        SUM(S.'TOTAL_SUBMISSIONS') AS 'TOTAL_SUBMISSIONS',
        SUM(S.'TOTAL_ACCEPTED_SUBMISSIONS') AS 'TOTAL_ACCEPTED_SUBMISSIONS'
      FROM 'SUBMISSION_STATS' S
      GROUP BY S.'CHALLENGE_ID'      
    ) SG ON CHA.'CHALLENGE_ID' = SG.'CHALLENGE_ID'
GROUP BY
    CON.'CONTEST_ID', CON.'HACKER_ID', CON.'NAME'
HAVING
    'TOTAL_SUBMISSIONS' +
    'TOTAL_ACCEPTED_SUBMISSIONS' +
    'TOTAL_VIEWS' +
    'TOTAL_UNIQUE_VIEWS' <> 0
ORDER BY
    CON.'CONTEST_ID';
